FHIR:
    app_id: my_web_app
    api_base: http://localhost:8080/fhir/
H2O:
    HOST_URL: http://localhost:7860
DATA:
    path: data/raw_data.csv
    sep: ;
LLM:
    headers: [conditions, observations, medications, procedures]
    headers_with_parameters: [observations, medications]
    ignore_phrases: [not available, none listed]
    system_prompt: |
        Do not provide any explanations and just extract medical events (ignore future events or suggested medical plans) from the text below in the following format:

        conditions: <semicolon-separated list of patient's conditions, symptoms and diagnoses>
        observations: <semicolon-separated list of observations such as lab data, measurements, vital signs, clinical findings and various scores, each in format observation (value)>
        medications: <semicolon-separated list of statements about medication use by the patient each with medication name and dose and frequency information if available in format medication (dose, frequency)>
        procedures: <semicolon-separated list of procedures and therapies and tests performed on the patient>

        Text:
